import{a as S,S as q,i as a}from"./assets/vendor-CucEYOFD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const v="56510220-94bf2d241d837d21bc9d081cd",E="https://pixabay.com/api/",M=15;async function p(r,t){return(await S.get(E,{params:{key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:M}})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),g=document.querySelector(".load-more-btn"),R=new q(".gallery a",{captionsData:"alt",captionDelay:250});function h(r){const t=r.map(({webformatURL:i,largeImageURL:c,tags:e,likes:o,views:n,comments:w,downloads:P})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${c}">
            <img class="gallery-image" src="${i}" alt="${e}" />
          </a>
          <div class="image-info">
            <p><span>Likes</span>${o}</p>
            <p><span>Views</span>${n}</p>
            <p><span>Comments</span>${w}</p>
            <p><span>Downloads</span>${P}</p>
          </div>
        </li>
      `).join("");f.insertAdjacentHTML("beforeend",t),R.refresh()}function $(){f.innerHTML=""}function y(){m.classList.remove("is-hidden")}function L(){m.classList.add("is-hidden")}function B(){g.classList.remove("is-hidden")}function u(){g.classList.add("is-hidden")}const O=document.querySelector(".form"),A=document.querySelector(".load-more-btn"),_=15;let l="",s=1,d=0;O.addEventListener("submit",x);A.addEventListener("click",D);async function x(r){if(r.preventDefault(),l=r.currentTarget.elements["search-text"].value.trim(),!l){a.error({message:"Please enter a search query.",position:"topRight"});return}s=1,d=0,$(),u(),y();try{const t=await p(l,s);if(t.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}d=Math.ceil(t.totalHits/_),h(t.hits),b()}catch{a.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L()}}async function D(){s+=1,u(),y();try{const r=await p(l,s);h(r.hits),b(),G()}catch{a.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L()}}function b(){if(s>=d){u(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}B()}function G(){const r=document.querySelector(".gallery-item");if(!r)return;const t=r.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
