import{a as P,S,i as n}from"./assets/vendor-CucEYOFD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function c(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=c(e);fetch(e.href,r)}})();const q="56510220-94bf2d241d837d21bc9d081cd",M="https://pixabay.com/api/",B=15;async function m(o,t){return(await P.get(M,{params:{key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:B}})).data}const p=document.querySelector(".gallery"),f=document.querySelector(".loader"),s=document.querySelector(".load-more-btn"),E=new S(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){const t=o.map(({webformatURL:c,largeImageURL:l,tags:e,likes:r,views:i,comments:v,downloads:w})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${l}">
            <img class="gallery-image" src="${c}" alt="${e}" />
          </a>
          <div class="image-info">
            <p><span>Likes</span>${r}</p>
            <p><span>Views</span>${i}</p>
            <p><span>Comments</span>${v}</p>
            <p><span>Downloads</span>${w}</p>
          </div>
        </li>
      `).join("");p.insertAdjacentHTML("beforeend",t),E.refresh()}function R(){p.innerHTML=""}function h(){f.classList.remove("is-hidden")}function y(){f.classList.add("is-hidden")}function $(){s.classList.remove("is-hidden"),s.classList.remove("is-invisible")}function L(){s.classList.add("is-hidden"),s.classList.remove("is-invisible")}function O(){s.classList.add("is-invisible")}function A(){s.classList.remove("is-invisible")}const _=document.querySelector(".form"),x=document.querySelector(".load-more-btn"),I=15;let d="",a=1,u=0;_.addEventListener("submit",D);x.addEventListener("click",G);async function D(o){if(o.preventDefault(),d=o.currentTarget.elements["search-text"].value.trim(),!d){n.error({message:"Please enter a search query.",position:"topRight"});return}a=1,u=0,R(),L(),h();try{const t=await m(d,a);if(t.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}u=Math.ceil(t.totalHits/I),g(t.hits),b()}catch{n.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{y()}}async function G(){a+=1,O(),h();try{const o=await m(d,a);g(o.hits),b(),H()}catch{n.error({message:"Something went wrong. Please try again later.",position:"topRight"}),A()}finally{y()}}function b(){if(a>=u){L(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}$()}function H(){const o=document.querySelector(".gallery-item");if(!o)return;const t=o.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
